### PR TITLE
Fix depiction php

### PR DESCRIPTION
**Pull request by Geczy**

### CODE REVIEW

**Comment by Geczy** [comment]
Will work for you now. Just have to repackage your DEBs with the depiction in the Control file

**Comment by Geczy** [comment]
Instead of repackaging every deb you can also just modify the Packages file (one in bz2 too)

**Comment by arcticsn0w** [comment]
Woah, thanks! xD

**Comment by arcticsn0w** [comment]
Agh. I opened up MarkAsRead7 (iOS 8) in the repo, but it still doesn't work. Let me try redoing the depiction link.

**Comment by Geczy** [comment]
Github pages does not support PHP

**Comment by arcticsn0w** [comment]
Ah. I'm just going to do a very simple text-based depiction for my packages, but that looks nice. Too bad I can't use it :p

**Comment by Geczy** [comment]
So much duplication that way, headers and footer and a new file for each package :cry:

**Pull request merged**
